#!/bin/sh

# Set these paths appropriately

BIN=/Applications/Treetagger/bin
CMD=/Applications/Treetagger/cmd
LIB=/Applications/Treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
