#!/bin/sh

# Set these paths appropriately

BIN=/Applications/Treetagger/bin
CMD=/Applications/Treetagger/cmd
LIB=/Applications/Treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
